sudo: required

services:
    - docker

install:
    - 'echo "ABSTRACT_API_API_KEY=${ABSTRACT_API_API_KEY}" > .env'
    - docker-compose pull
    - bin/composer install --prefer-dist

script:
    - bin/run_tests
    - bin/run_tests behat
