version: '3'

services:
    php:
        build: docker/php/
        image: matthiasnoback/decoupling-from-infrastructure-workshop-web
        volumes:
            - ./:/app:cached
        working_dir: /app
        user: ${HOST_UID}:${HOST_GID}

    composer:
        image: composer:latest
        volumes:
            - ./:/app:cached
        user: ${HOST_UID}:${HOST_GID}
